functionname(){
    const randanumbet = new Promise((resolve,reject))=>
{
    settime (())=> {
        resolve((Math.ceil(random%2)*10)+1)
    }, 1000);
  });
}
generateRandomNumber.then{(res)=>{
    console.log('error while showing reults': ' +err);
   }).catch(err => )
 })
}
//b
let something = async () => {
    try {
        await generateRandomNumber()
    }catch (error){
        console.log('Error occured')
    }
}
something()uy